spring.cloud.stream.function.routing.enabled=true
spring.cloud.stream.bindings.functionRouter-in-0.destination=pn-paper-event-enrichment-input,pn-paper-archives
spring.cloud.stream.sqs.bindings.functionRouter-in-0.consumer.snsFanout=false

spring.application.name=PN-splitCon020
spring.codec.max-in-memory-size=150MB


#logging.config=classpath:logback-base.xml
pn.env.runtime=PROD
pn.middleware.init.aws=true
pn.log.trace-id-header=x-trace-id

aws.profileName=sso_pn-core-dev
aws.regionCode=eu-central-1
aws.region=eu-central-1


# Application parameters
pn.splitcon020.eventInputQueueName=pn-paper-event-enrichment-input
pn.splitcon020.archiveToUnpackageQueueName=pn-paper-archives
pn.splitcon020.paperEventEnrichmentTable=pn-PaperChannelEventEnrichment


pn.splitcon020.safeStorageBaseUrl=http://localhost:9090/
pn.splitcon020.safeStorageUser=pn-test



